# Generated by Django 3.0 on 2020-01-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SniffingJobModel',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('pid', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField()),
                ('json_file', models.CharField(max_length=250)),
                ('pcap_file', models.CharField(max_length=250)),
                ('_interfaces', models.TextField()),
            ],
        ),
    ]
