# Generated by Django 3.0 on 2020-01-03 16:30

from django.db import migrations, models
import signal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SniffingJobModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveIntegerField(default=signal.Signals['SIGCONT'])),
                ('filters', models.CharField(max_length=500, null=True)),
                ('_interfaces', models.TextField()),
                ('json_file', models.CharField(max_length=250)),
                ('pcap_file', models.CharField(max_length=250, null=True)),
                ('pid', models.PositiveIntegerField()),
                ('_pid_file', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
