# Generated by Django 3.0.2 on 2020-01-06 16:28

from django.db import migrations, models
import django.utils.timezone
import signal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SniffingJobModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveIntegerField(default=signal.Signals['SIGCONT'])),
                ('filters', models.TextField(null=True)),
                ('_interfaces', models.TextField()),
                ('json_file', models.CharField(max_length=250)),
                ('pcap_file', models.CharField(max_length=250, null=True)),
                ('pid', models.PositiveIntegerField()),
                ('_pid_file', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
