# Generated by Django 3.0.2 on 2020-01-29 13:05

from django.db import migrations, models
import django.utils.timezone
import signal


class Migration(migrations.Migration):

    dependencies = [
        ('black_widow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebParsingJobModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveIntegerField(default=signal.Signals['SIGCONT'])),
                ('pid', models.PositiveIntegerField()),
                ('_pid_file', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parsing_type', models.CharField(choices=[('1', 'Single Page'), ('2', 'Website Crawling')], max_length=50)),
                ('depth', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
