# Generated by Django 3.0 on 2020-01-03 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('black_widow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sniffingjobmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
