# Generated by Django 3.0 on 2020-01-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_widow', '0002_sniffingjobmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sniffingjobmodel',
            name='_pid_file',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sniffingjobmodel',
            name='pid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
