MY_IP='my_ip'
SERVER_TO_ATTACK='server_to_attack'
SERVER_TO_DEFEND='server_to_defend'
GAME_SERVER='game_server'
TEAM_PLAYER='team_players'
TEAM_TOKEN='team_token'
SUBMIT_URL='submit_url'
FLAG_REGEX='flag_regex'
